name: CI/CD pipeline
run-name: Building and deploying factorial app
on:
  push:
    branches:
    - main

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Installing python on a runner server
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Unit testing
        run: python3 -m unittest test_factorial.py

  Build-deploy:
    needs: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_NAME }}/test_rep:latest